pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        echo 'Building...'
        sh 'rm -rf node_modules package-lock.json'
        sh 'npm install'
        sh 'npm run build'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying...'
        sh 'pm2 startOrRestart ecosystem.config.pro.js --env production'
      }
    }
  }
}