import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import ClassDetailInfo from "@/components/class/class-detail-info";

const ClassDetail = () => {
  const router = useRouter();
  const { cid } = router.query;

  return (
    <>
      <Head>
        <title>Paputea | Thông tin lớp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="container">
        <ClassDetailInfo classCode={cid} className="container" />
      </div>
    </>
  );
};

export default ClassDetail;
