import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import ClassDetail from "@/components/class/class-detail";

const Class = () => {
  const router = useRouter();
  const { classCode } = router;

  return (
    <>
      <Head>
        <title>Paputea | Thông tin lớp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="container">ABC {classCode}</div>
      {/* <ClassDetail className="container">{classCode}</ClassDetail> */}
    </>
  );
};

export default Class;
