import Head from "next/head";
import List from "@/components/class/class-list";

function ClassList() {
  return (
    <>
      <Head>
        <title>Paputea | Danh sách lớp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="container">
        <List />
      </div>
    </>
  );
}

export default ClassList;
