import Head from "next/head";
import TutorRule from "@/components/notes/tutor-rule";

function Note() {
  return (
    <>
      <Head>
        <title>Paputea | Quy định khi nhận lớp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="container">
        <TutorRule />
      </div>
    </>
  );
}

export default Note;
