import Head from "next/head";
import Head from "next/head";

import AboutInfo from "../components/about/about";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <AboutInfo />
    </>
  );
}
