import Head from "next/head";

import AboutInfo from "@/components/about/about-info";
import classes from "@/styles/about.module.css";

function Home() {
  return (
    <>
      <Head>
        <title>Paputea | Thông tin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={classes.main}>
        <div className="container section">
          <h1 className="title is-1 color-primary">Thư ngỏ</h1>
          <AboutInfo />
          <p>Hãy liên hệ với chúng tôi để được hỗ trợ tư vấn!</p>
          <p>Thân ái!</p>
        </div>
      </div>
    </>
  );
}

export default Home;
