import Head from "next/head";
import Image from "next/image";

import FormRegistrationHero from "@/components/home/form-registraion-hero";
import OnlineServiceHero from "@/components/home/online-service-hero";
import TutorHero from "@/components/home/tutor-hero";
import AboutInfo from "@/components/about/about-info";
import TuitionInfo from "@/components/tuition/tuition-info";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <>
        <div className="container">
          <FormRegistrationHero />
        </div>
        <div className="container">
          <section className="hero is-medium">
            <div className="hero-body pt-1">
              <AboutInfo />
            </div>
          </section>
        </div>
        <OnlineServiceHero />
        <section className="hero is-medium">
          <div className="hero-body pb-1">
            <TuitionInfo />
          </div>
        </section>
        <TutorHero />
      </>
    </>
  );
}
