import Head from "next/head";

import TuitionInfo from "@/components/tuition/tuition-info";

function Tuition() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="container">
        <TuitionInfo />
      </div>
    </>
  );
}

export default Tuition;
