import Head from "next/head";
import OnlineDescribe from "@/components/notes/online-describe";

function Describe() {
  return (
    <>
      <Head>
        <title>Paputea | Ưu điểm học trực tuyến</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="container">
        <OnlineDescribe />
      </div>
    </>
  );
}

export default Describe;
